FROM python:3.10.9


WORKDIR /fast


COPY  ./bot /fast
COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt
RUN apt-get update && apt-get install -y gcc libffi-dev && apt-get clean


CMD ["uvicorn", "fastlink:app", "--host", "0.0.0.0", "--port", "8001"]