FROM python:3.10.9

WORKDIR /app
RUN #useradd -m celeryuser
# Копируем файлы проекта Django
COPY ./taskmanager /taskmanager
COPY requirements.txt ./
# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt
#RUN pip install -r requirements.txt
#USER celeryuser
EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]