# Generated by Django 5.1.3 on 2024-12-04 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='days',
        ),
        migrations.AddField(
            model_name='subscription',
            name='remaining_time',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
