# Generated by Django 5.1.3 on 2024-12-04 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_subscription_days_subscription_remaining_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='remaining_time',
            new_name='days',
        ),
    ]
