# Generated by Django 5.1.3 on 2024-12-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_remaining_time_subscription_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='try_promocode',
            field=models.IntegerField(default=0),
        ),
    ]
