# Generated by Django 5.1.3 on 2024-12-10 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_subscription_try_promocode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользовательи'},
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='replenished',
        ),
        migrations.AddField(
            model_name='subscription',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='pay',
            field=models.BooleanField(default=False, verbose_name='Пополнено ли средств'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='replenished',
            field=models.IntegerField(default=0, verbose_name='Пополнено'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='days',
            field=models.IntegerField(default=0, verbose_name='Количество дней промокода'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='promo',
            field=models.CharField(max_length=255, verbose_name='Сам промокод'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='days',
            field=models.DurationField(default=datetime.timedelta, verbose_name='Время подписки'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='promocode',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Активный промокод'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='task',
            field=models.BooleanField(default=False, verbose_name='Запущена ли фоновая задача (убаление времени)'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='try_promocode',
            field=models.IntegerField(default=0, verbose_name='Попытка ввести промокод'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='unique_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Код vless'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user_id',
            field=models.BigIntegerField(verbose_name='Id тпользователя в тг'),
        ),
    ]
