# Generated by Django 5.1.3 on 2024-12-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='promocode',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID рекламной компании'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='task',
            field=models.BooleanField(default=False, verbose_name='Запущена ли фоновая задача (Убавление времени)'),
        ),
    ]
