# Generated by Django 5.1.3 on 2024-12-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_subscription_options_promocode_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='promocode',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID рекламной кампании'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Кампания'),
        ),
    ]
