# Generated by Django 5.1.3 on 2024-12-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_promotion_alter_promocode_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='promocode',
            field=models.TextField(blank=True, null=True, verbose_name='Активный промокод'),
        ),
    ]
