# Generated by Django 5.1.3 on 2024-12-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_subscription_promocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='promocode',
            field=models.TextField(blank=True, default=' ', null=True, verbose_name='Активный промокод'),
        ),
    ]
