# Generated by Django 5.1.3 on 2025-01-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_subscription_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='look_promotion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
