# Generated by Django 5.1.3 on 2025-02-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_subscription_look_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
