# Generated by Django 5.1.3 on 2025-05-17 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_subscription_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='days',
        ),
    ]
