# Generated by Django 5.1.3 on 2025-05-17 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_subscription_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='days',
            field=models.DurationField(default=datetime.timedelta, verbose_name='Время подписки'),
        ),
    ]
