# Generated by Django 5.1.3 on 2025-05-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_subscription_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='days',
            field=models.IntegerField(default=0, verbose_name='Дни подписки'),
        ),
    ]
